import { defineConfig } from '@vben/oxfmt-config';

export default defineConfig({
  ignorePatterns: [
    'dist',
    'dev-dist',
    '.local',
    '.claude',
    '.agent',
    '.agents',
    '.codex',
    '.output.js',
    'node_modules',
    '.nvmrc',
    'coverage',
    'CODEOWNERS',
    '.nitro',
    '.output',
    '**/*.svg',
    '**/*.sh',
    'public',
    'apps/web-naive/src/views/content/image-upload-field.vue',
    'apps/web-naive/src/views/content/link/index.vue',
    'apps/web-naive/src/views/content/picture-album/index.vue',
    'apps/web-naive/src/views/content/picture/index.vue',
    'apps/web-naive/src/views/content/tag/index.vue',
    'apps/web-naive/src/views/content/website-category/index.vue',
    'apps/web-naive/src/views/content/website/index.vue',
    'apps/web-naive/src/views/operation/job/index.vue',
    'apps/web-naive/src/views/operation/notice/index.vue',
    'apps/web-naive/src/views/operation/restriction/index.vue',
    'apps/web-naive/src/views/operation/source/index.vue',
    'apps/web-naive/src/views/system/menu/index.vue',
    '.npmrc',
    '*-lock.yaml',
    'skills-lock.json',
  ],
});
